main: com.shardbytes.safearea.SafeArea
name: SafeArea
version: "1.2"
api-version: "1.16"
author: ShardBytes (plajdo)
website: shardbytes.com
description: Create safe areas where mobs cannot spawn.
commands:
  sa-test:
    description: Test if plugin is installed correctly.
    usage: /sa-test
    permission: safearea.test
    permission-message: You do not have permissions to test this plugin.

  sa-check:
    description: Check if you are standing inside a safe area.
    usage: /sa-check
    permission: safearea.check
    permission-message: You do not have permissions to check whether you are standing inside a safe area.

  sa-create:
    description: Create a new safe area.
    usage: /sa-create <x1> <y1> <z1> <x2> <y2> <z2>
    permission: safearea.edit
    permission-message: You do not have permissions to remove or create safe areas.

  sa-remove:
    description: Remove the safe area the player is standing in.
    usage: Stand in a safe area you want to remove and type /sa-remove
    permission: safearea.edit
    permission-message: You do not have permissions to remove or create safe areas.

  sa-list:
    description: Show all safe areas.
    usage: /sa-list
    permission: safearea.list
    permission-message: You do not have permissions to list safe areas.

permissions:
  safearea.test:
    description: Allows to test if this plugin is installed correctly.
    default: op

  safearea.check:
    description: Allows to check whether you are standing inside a safe area.
    default: op

  safearea.edit:
    description: Allows to create and remove safe areas.
    default: op

  safearea.list:
    description: Allows to see all created safe areas.
    default: op

  safearea.*:
    description: Wildcard permission for all SafeArea commands.
    default: op
    children:
      safearea.test: true
      safearea.edit: true
      safearea.list: true
      safearea.check: true